name: Manual API Caller

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Data to send'
        required: true
        default: 'Hello from GitHub Actions!'

jobs:
  call-api:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Ensuring the job has permission to access the OIDC token
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Call API with OIDC Token
      env:
        OIDC_TOKEN: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}  # Using the automatically injected environment variable
      run: |
        curl -X POST "https://charming-termite-surely.ngrok-free.app" \
        -H "Authorization: Bearer $OIDC_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"data": "${{ github.event.inputs.message }}"}'
