name: API Interaction with OIDC Authentication

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  example_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get JWT from GitHub
      shell: sh
      run: |
        i=1
        while [ "${i}" -le 5 ]; do
          JWT_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                           -H "Accept: application/json; api-version=2.0" \
                           "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=YOUR_AUDIENCE" | jq -r '.value')
          if [ -n "$JWT_TOKEN" ] && [ "$JWT_TOKEN" != "null" ]; then
            echo "::add-mask::$JWT_TOKEN"
            echo "JWT_TOKEN=$JWT_TOKEN" >> "$GITHUB_ENV"
            break
          else
            echo "Attempt $i failed. Retrying in 15 seconds..."
            sleep 15
          fi
          i=$((i + 1))
        done

    - name: Check that token isn't empty
      shell: sh
      run: |
        if [ -z "${JWT_TOKEN}" ]; then
            echo "Error: JWT_TOKEN is empty! Ensure 'id-token: write' is set in permissions."
            exit 1
        else
            echo "JWT Token successfully retrieved and stored."
        fi

    - name: Post to API with JWT Token
      shell: sh
      run: |
        RESPONSE=$(curl -X POST -H "Authorization: Bearer ${JWT_TOKEN}" \
                                -H "Content-Type: application/json" \
                                -d '{"message": "Hello from GitHub Actions!"}' \
                                "https://charming-termite-surely.ngrok-free.app")
        echo "Response from API: $RESPONSE"

      
