name: API Interaction with OIDC Authentication

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  example_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get JWT from GitHub
      shell: bash
      run: |
        JWT_TOKEN=$(curl -s -H "Authorization: bearer ${{ github.token }}" \
                            -H "Accept: application/json;api-version=2.0" \
                            "${{ github.api_url }}/actions/oidc/token" \
                            -d '{"audience":"api://trusty"}' | jq -r '.value')
        echo "JWT_TOKEN=$JWT_TOKEN" >> $GITHUB_ENV
        echo "::add-mask::$JWT_TOKEN"

    - name: Check that token isn't empty
      shell: bash
      run: |
        if [ -z "${{ env.JWT_TOKEN }}" ]; then
            echo "Error: JWT_TOKEN is empty! Ensure 'id-token: write' is set in permissions."
            exit 1
        else
            echo "JWT Token successfully retrieved and stored."
        fi

    - name: Post to API with JWT Token
      shell: bash
      run: |
        RESPONSE=$(curl -X POST -H "Authorization: Bearer ${{ env.JWT_TOKEN }}" \
                                -H "Content-Type: application/json" \
                                -d '{"message": "Hello from GitHub Actions!"}' \
                                "https://charming-termite-surely.ngrok-free.app")
        echo "Response from API: $RESPONSE"
