name: API Interaction with OIDC Authentication

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  interact-with-api:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read


    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Get OIDC token and use it
      run: |
        OIDC_TOKEN=$(curl -H "Authorization: bearer ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}" \
                           -H "Accept: application/json; api-version=2.0" \
                           "${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}&audience=YOUR_AUDIENCE" | jq -r '.value')
        echo "OIDC_TOKEN=${OIDC_TOKEN}" >> $GITHUB_ENV
        echo "::add-mask::${OIDC_TOKEN}"
        
        # Use the OIDC_TOKEN for subsequent POST request
        curl -X POST -H "Authorization: Bearer ${OIDC_TOKEN}" \
             -H "Content-Type: application/json" \
             -d '{"message": "Hello from GitHub Actions!"}' \
             "https://charming-termite-surely.ngrok-free.app"
