name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: PR Size Labeler
      uses: lukehinds/label-pr-size@v0.0.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        base-sha: ${{ github.event.pull_request.base.sha }}
        head-sha: ${{ github.event.pull_request.head.sha }}
        repository: ${{ github.repository }}
        pr-number: ${{ github.event.pull_request.number }}
